### ISSUE TITLE
Rename project so it is valid according to NPM guidelines

### ISSUE THREAD

**Issue by thomasfr** [magnetik/node-webid#1]
See http://npmjs.org/doc/developers.html

> name: This should be a string that identifies your project. Please do not use the name to specify that it runs on node, or is in
> JavaScript. You can use the "engines" field to explicitly state the versions of node (or whatever else) that your program
> requires, and it's pretty well assumed that it's javascript.
> 
> It does not necessarily need to match your github repository name.
> 
> So, **node-foo** and bar-js are **bad names**. foo or bar are better.

**Comment by magnetik** [comment]
It has been sended to npm as 'webid' : http://search.npmjs.org/#/webid

**Comment by thomasfr** [comment]
Great. Thank you for this module! ;)
